name: Test Gmail App Password

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install nodemailer
      - name: Send test email
        run: node email_test.js
