name: Run Price Trigger Script

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GROWATT_API_TOKEN: ${{ secrets.GROWATT_API_TOKEN }}
      GROWATT_DEVICE_SN: ${{ secrets.GROWATT_DEVICE_SN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up grow.mjs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node grow.mjs
