name: Send Email Notification

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email via Brevo SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 🚀 GitHub Action Notification
          to: v75bong@gmail.com
          from: 907ac7001@smtp-brevo.com
          body: |
            Hello,

            This is an automated email sent from a GitHub Action using Brevo SMTP.

            ✅ The workflow ran successfully on the `main` branch.

            Cheers,
            GitHub Actions Bot
